# Usa una imagen oficial de Node
FROM node:18-alpine

# Crea el directorio de la app
WORKDIR /usr/src/app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala dependencias
RUN npm install --production

# Copia el resto del código
COPY . .

# Expone el puerto definido en la app
EXPOSE 3000

# Comando para ejecutar el backend
CMD ["node", "src/app.js"]
